version: '2.4'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "5985:5985"
    volumes:
      - /efs/tmp/nginx.conf:/etc/nginx/nginx.conf
      - /app:/app
      - /tmp:/data/nginx/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
  couchdbone:
    cpus: 0.99
    image: couchdb:3.3.1
    restart: always
    environment:
      - COUCHDB_USER=1
      - COUCHDB_PASSWORD=1
    volumes:
      - /efs/tmp/default.ini:/opt/couchdb/etc/default.ini
      - /efs/tmp/local.ini:/opt/couchdb/etc/local.ini
      - /efs/db:/opt/couchdb/data
    ports:
      - "5984:5984"
    extra_hosts:
      - "host.docker.internal:host-gateway"
