export const titles: { [key: string]: string } = {
	"1": "All about [username]: From their profile to their photos, get the inside scoop on this Twitter superstar",
	"2": "Browse [username]'s Twitter profile to discover their latest photos, thoughts, and insights",
	"3": "Check out [username]'s Twitter photos and profile to see what makes this social media influencer stand out",
	"4": "Discover the world of [username] through their Twitter profile and photos, and join the conversation today",
	"5": "Explore [username]'s Twitter profile for an inside look at their life and interests, with photos and more",
	"6": "Follow [username] on Twitter to stay up-to-date on their latest profile updates, photos, and tweets",
	"7": "Get to know [username] on Twitter through their profile, photos, and engaging tweets",
	"8": "Have you checked out [username]'s Twitter profile yet? Discover their photos, interests, and more today",
	"9": "Questioning the status quo with [username]: A Twitter influencer's perspective",
	"0": "Rising to the top: [username]'s journey to Twitter fame",
	"-": "Looking for [username]'s Twitter profile? Look no further! See their photos, thoughts, and more",
	"a": "An insider's look into the world of [username], Twitter's rising star",
	"b": "Behind the tweets: [username]'s journey to social media success",
	"c": "Candid conversations with [username]: A Twitter influencer's story",
	"d": "Discovering the secrets of [username]'s Twitter feed",
	"e": "Exploring the mind of [username], a Twitter mastermind",
	"f": "Following in the footsteps of [username]: Twitter tips and tricks",
	"g": "Getting to know [username]: A Twitter celebrity in the making",
	"h": "Hanging out with [username]: An exclusive interview with a Twitter icon",
	"i": "Inside [username]'s Twitter strategy: A closer look at the tactics of a social media pro",
	"j": "Journeying through the tweets of [username], a Twitter trailblazer",
	"k": "Keeping up with [username]: A day in the life of a Twitter sensation",
	"l": "Learning from [username]: How to grow your Twitter following like a pro",
	"m": "Meet [username]: The Twitter star that's taking the social media world by storm",
	"n": "Navigating the world of Twitter with [username]: Tips from a social media expert",
	"o": "On the cutting edge of Twitter: An inside look at [username]'s social media strategy",
	"p": "Picking the brain of [username]: Insights from a Twitter thought leader",
	"q": "Questioning the status quo with [username]: A Twitter influencer's perspective",
	"r": "Rising to the top: [username]'s journey to Twitter fame",
	"s": "Stepping into the shoes of [username]: What it takes to succeed on Twitter",
	"t": "Talking Twitter with [username]: An interview with a social media superstar",
	"u": "Uncovering the secrets of [username]'s Twitter success",
	"v": "Venturing into the world of [username]: A Twitter influencer's guide",
	"w": "Walking in [username]'s footsteps: Lessons in Twitter success",
	"x": "X-raying the tweets of [username]: A deep dive into the social media habits of a pro",
	"y": "Yearning for Twitter success? Learn from [username], the social media star",
	"z": "Zooming in on [username]'s Twitter strategy: How to build a thriving online presence"
}
export const descriptions = {
	"1": "An insider's look into the world of [username], Twitter's rising star",
	"2": "Behind the tweets: [username]'s journey to social media success",
	"3": "Candid conversations with [username]: A Twitter influencer's story",
	"4": "Discovering the secrets of [username]'s Twitter feed",
	"5": "Exploring the mind of [username], a Twitter mastermind",
	"6": "Following in the footsteps of [username]: Twitter tips and tricks",
	"7": "Getting to know [username]: A Twitter celebrity in the making",
	"8": "Hanging out with [username]: An exclusive interview with a Twitter icon",
	"9": "Inside [username]'s Twitter strategy: A closer look at the tactics of a social media pro",
	"0": "Journeying through the tweets of [username], a Twitter trailblazer",
	"-": "Keeping up with [username]: A day in the life of a Twitter sensation",
	"a": "All about [username]: From their profile to their photos, get the inside scoop on this Twitter superstar",
	"b": "Browse [username]'s Twitter profile to discover their latest photos, thoughts, and insights",
	"c": "Check out [username]'s Twitter photos and profile to see what makes this social media influencer stand out",
	"d": "Discover the world of [username] through their Twitter profile and photos, and join the conversation today",
	"e": "Explore [username]'s Twitter profile for an inside look at their life and interests, with photos and more",
	"f": "Follow [username] on Twitter to stay up-to-date on their latest profile updates, photos, and tweets",
	"g": "Get to know [username] on Twitter through their profile, photos, and engaging tweets",
	"h": "Have you checked out [username]'s Twitter profile yet? Discover their photos, interests, and more today",
	"i": "Interested in learning more about [username]? Check out their Twitter profile for photos, updates, and more",
	"j": "Join [username]'s Twitter community and discover their profile, photos, and engaging tweets",
	"k": "Keep up with [username]'s latest photos and updates by following their Twitter profile today",
	"l": "Looking for [username]'s Twitter profile? Look no further! See their photos, thoughts, and more",
	"m": "Meet [username] on Twitter and explore their profile, photos, and engaging content",
	"n": "Navigate [username]'s Twitter profile to discover their latest photos, updates, and insights",
	"o": "Obsessed with [username]'s Twitter photos? Follow their profile for even more engaging content",
	"p": "Peruse [username]'s Twitter profile and discover their photos, thoughts, and more",
	"q": "Questions about [username]'s social media presence? Check out their Twitter profile for photos and insights",
	"r": "Ready to follow a Twitter influencer? Look no further than [username]'s profile, featuring photos and more",
	"s": "Stay up-to-date on [username]'s latest photos and updates by following their Twitter profile today",
	"t": "Take a peek into the life of [username] through their Twitter profile, featuring photos and engaging content",
	"u": "Uncover the secrets of [username]'s social media presence by exploring their Twitter profile, with photos and more",
	"v": "View [username]'s Twitter profile for an inside look at their life and interests, with photos and engaging content",
	"w": "Want to learn more about [username]? Check out their Twitter profile for photos, updates, and insights",
	"x": "X marks the spot for engaging content! Follow [username] on Twitter to discover their profile and photos",
	"y": "Yearning for more social media content? Explore [username]'s Twitter profile for photos, thoughts, and more",
	"z": "Zero in on [username]'s social media presence by checking out their Twitter profile, featuring photos and engaging content"
}