version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - /efs/tmp/nginx.conf:/etc/nginx/nginx.conf
      - /app:/app
    extra_hosts:
      host.docker.internal: 192.168.1.100
  couchdbone:
    image: couchdb:3.3.1
    restart: always
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    volumes:
      - /efs/tmp/default.ini:/opt/couchdb/etc/default.ini
      - /efs/tmp/local.ini:/opt/couchdb/etc/local.ini
      - /efs/couchdb:/opt/couchdb/data
    ports:
      - "5984:5984"
  # envoy:
  #   image: envoyproxy/envoy:v1.19-latest
  #   volumes:
  #     - /efs/tmp/envoy.yaml:/etc/envoy/envoy.yaml
  #   ports:
  #     - "80:80"
  #     - "4001:3001"
  #     - "4002:3002"
  #     - "4003:3003"
